services:
    app.subscriber:
            class: AppBundle\EventListener\AppSubscriber
            arguments:
                - "@service_container"
            tags:
                - { name: kernel.event_subscriber }
